### ISSUE TITLE
关于显示设置

### ISSUE THREAD

**Issue by Koorin** [poooi/poi#1072]
不知道能不能在UI设置那里添加可以选择横版布局的信息栏在左边或右边，强迫症表示习惯左边看舰队一览游戏画面在右边_(:з」∠)_

**Comment by KochiyaOcean** [comment]
显示设置 - 自定义 css，输入
```css
poi-main {
  flex-flow: row-reverse nowrap;
}
```
保存然后换个主题
效果差不多就这种感觉

![image](https://cloud.githubusercontent.com/assets/8194131/16194673/54903076-3728-11e6-8032-292d499c0de2.png)
