### ISSUE TITLE
关于页面布局的一点小建议

### ISSUE THREAD

**Issue by ShiinaGensho** [poooi/poi#1316]
**poi 版本 / poi version:**
7.3.0

**操作系统 / OS:**
Mac OS X 10.12.3

**你遇到了什么样的问题 / The problem you've met:**
建议增加横向布局时插件和其他内容上下排布，类似下图
![qq20170129-0](https://cloud.githubusercontent.com/assets/16795336/22397919/13ce120a-e5c0-11e6-94dd-6955c1271c97.png)

**Comment by KochiyaOcean** [comment]
仅仅在特定尺寸窗口下具有良好显示效果，不具备通用性，建议使用自定义 css 实现

**Comment by KochiyaOcean** [comment]
显示设置 - 自定义 css
```css
.poi-tabs-container {
  flex-direction: column;
}
.poi-tabs-container > div {
  height: 510px;
}
.poi-tabs-container > div:nth-child(2) {
  overflow-y: auto;
}
```
保存后切换主题生效
大概这种感觉
![image](https://cloud.githubusercontent.com/assets/8194131/22398003/989e1f90-e5b9-11e6-90ae-682cbbba62e9.png)
