### ISSUE TITLE
设定通知时间

### ISSUE THREAD

**Issue by VongolaXI11** [poooi/poi#1414]
**poi 版本 / poi version:**
7.5.2

**操作系统 / OS:**
win7(64x)

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
在基本设定的部分，若是面板太小，设定通知时间的数字会显示不出来。（如附图）
![image](https://cloud.githubusercontent.com/assets/12935733/25043461/cb04b41a-2152-11e7-8f00-a8a7aa41d513.png)
另外，既然可以调远征的通知时间了，入渠的是否也可以改呢？

**有没有重现的方法，或者与问题相关的任何信息 / The way to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
这个和主题的关系更大一点（虽然 poi 内置了不少主题，但并不是每个主题都好用的

**Comment by VongolaXI11** [comment]
真的欸，不过我比较喜欢暗色系的说，其他配色太亮了……
那么另一个问题有办法处理吗？关于入渠的通知时间那部分的。

**Comment by KagamiChan** [comment]
远征通知是为了可以提前准备好收远征，入渠时间通知是为了提前准备好点入渠吗

**Comment by VongolaXI11** [comment]
也是为了要提早准备帮舰娘们舔干净啊！（误

好啦其实是因为我不管入渠或是远征都会自动加两分钟
我不明白是什么问题
若是照预设的通知时间回收的话
不但没有吃到提前一分钟的好处
反而会比原订的时间还多一分钟

**Comment by KochiyaOcean** [comment]
@VongolaXI11 远征时间和预期不同的话请校对系统时间设置哦

**Comment by VongolaXI11** [comment]
哦喔搞定了！原来我的时间没有网络同步……谢谢你们！^^

**Comment by KagamiChan** [comment]
暗色系的主题还有几个，都可以试试看

**Comment by VongolaXI11** [comment]
嗯嗯不过我偏好这个:3

**Comment by KagamiChan** [comment]
可以使用自定义 css 在里面加上

``` css
.input-group-sm > .form-control, 
.input-group-sm > .input-group-addon, 
.input-group-sm > .input-group-btn > .btn {
  padding: 5px;
}
```

应该能有所改善，可以学一下 css 自己调
