### ISSUE TITLE
poi 7.6.0 在触摸屏上存在双击问题

### ISSUE THREAD

**Issue by EdiTurn** [poooi/poi#1423]
**poi 版本 / poi version:**
7.6.0 - beta 0

**操作系统 / OS:**
Windows 10 Pro 15063.138
通过 Android 端的 Remote Desktop 连接。

**你遇到了什么样的问题 / The problem you've met:**
当使用触摸模式控制 poi 时出现双击问题，比如远征中点击「决定」会自动派出第二舰队，翻页点击页码会变成连续翻页两次。
若使用 Remote Desktop 的鼠标指针模式则不存在此问题。

**Comment by KochiyaOcean** [comment]
@EdiTurn 和 7.5.0 相比并没有修改这方面的代码，确定 7.5.0 没有么

**Comment by EdiTurn** [comment]
可以肯定，换回 7.5.2 症状消失。

**Comment by KochiyaOcean** [comment]
@EdiTurn 7.5.1 呢

**Comment by EdiTurn** [comment]
回退到 7.5.0 和 7.5.1 后此问题消失。

删除 poi 数据文件夹后 7.6.0 上也正常了，我再研究一下……

**Comment by EdiTurn** [comment]
接上，删除 poi 数据文件夹后，首次打开 poi 出现面板错位；然后重启登录，未出现双击问题；然后重启 poi 后问题再次出现。
期间未更改过任何设置、安装任何插件。

**Comment by EdiTurn** [comment]
经测试，https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1266/artifacts 是首个出现此问题的版本。

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1316/artifacts 这个呢

**Comment by EdiTurn** [comment]
@KochiyaOcean 没有双击问题

**Comment by KochiyaOcean** [comment]
@EdiTurn 在有双击问题的版本上自定义 css 看看哪个可能解决这个问题？
```css
kan-game {
  height: auto;
}
```
```js
poi-app {
  position: static;
}
```

**Comment by EdiTurn** [comment]
@KochiyaOcean 基于 7.6.0-beta0 的 release 版本进行了测试：
无论是单独使用以上任何一段 css，或同时使用这两段，都无助于解决此问题。

**Comment by KochiyaOcean** [comment]
@EdiTurn 比较奇怪的是引起这个问题的 commit 只更改了这些 CSS……

**Comment by KochiyaOcean** [comment]
@EdiTurn 或者在没有双击问题的版本上自定义 css？
```css
kan-game {
  height: 100vh;
}
```
```css
poi-app {
  position: relative;
}
```
```css
poi-info {
  width: calc(100% / 1);
}
```
```css
poi-info {
  transform: scale(1);
  transform-origin: 0 0;
}
```

**Comment by EdiTurn** [comment]
基于上面 1.0.1316 的 build 进行了测试：
单独添加这段 css 后出现了双击问题。
````css
    poi-info {
        transform: scale(1);
        transform-origin: 0 0;
    }
````

**Comment by KochiyaOcean** [comment]
@EdiTurn 再看看单独添加其中一条哪个会出现问题？

**Comment by EdiTurn** [comment]
单独使用以下 css 会出现问题：
````css
    poi-info {
        transform: scale(1);
    }
````

**Comment by KochiyaOcean** [comment]
@EdiTurn 唔，现在的问题是这个 css 并不能去掉……

**Comment by KochiyaOcean** [comment]
@EdiTurn 双击区域大概是什么地方？全部 flash 还是

**Comment by KochiyaOcean** [comment]
@EdiTurn 以及改成 scale3d(1,1,1) 呢

**Comment by EdiTurn** [comment]
poi 面板不受影响。

游戏的双击区域大约在建造——高速建造开关以下的部分，点击这个开关几率性出现双击（100%缩放，100%面板区域）。增大缩放或面板区域的宽度会使这个位置上移。

基于 1.0.1316 的 build ，单独添加这段 css 亦出现双击问题，双击区域同上。
````css
    poi-info {
        transform: scale3d(1,1,1);
    }
````

**Comment by KochiyaOcean** [comment]
@EdiTurn 也就是说可以理解为下图所在区域？
![image](https://cloud.githubusercontent.com/assets/8194131/25285270/3d82aca6-26ec-11e7-8a68-360891adcebc.png)

**Comment by EdiTurn** [comment]
@KochiyaOcean 高度上差不多，但是舰娘的改造按钮也收到影响。

**Comment by KochiyaOcean** [comment]
@EdiTurn 那么这样是否会有问题
````css
poi-info {
  transform: scale(1);
  pointer-events: none;
}
poi-control {
  pointer-events: all;
}
poi-map-reminder {
  pointer-events: all;
}
````
