### ISSUE TITLE
提示栏位置修改建议

### ISSUE THREAD

**Issue by SykieChen** [poooi/poi#1640]
希望可以修改 poi-info 的位置，现在统一放在 kan-game-warpper 里，当需要分离窗口运行（设置游戏分辨率为 0 x 0）时，或者需要配合 KCV 使用只记录数据时，只要游戏 flash 隐藏就会连带导致提示栏消失或不便查看。
![image](https://user-images.githubusercontent.com/5460009/33320808-60de7dde-d47e-11e7-9ff0-fc7582f04ab1.png)
当前我是用的方式是修改分辨率为 1 x 1，此时 poi-info 不会隐藏。修改布局为上下布局，可以使 poi-info 附着在面板底部。如图：
![image](https://user-images.githubusercontent.com/5460009/33320666-f447c748-d47d-11e7-9b3e-d65acd865a74.png)
但此时布局会自动切换为横向，面板数据横向排列，不符合纵向竖窗口。导致很多数据无法显示完全。如图：
![image](https://user-images.githubusercontent.com/5460009/33320643-e35814e2-d47d-11e7-9fc2-f5427214970c.png)
希望可以把 poi-info 挪到 poi-app 里，使得纵向布局和提示栏可以共存。
感谢。

**Comment by KochiyaOcean** [comment]
以维持现有布局为前提的情况下难以实现。

**Comment by SykieChen** [comment]
@KochiyaOcean 那是否可以添加一个设置，允许手动选择面板横向或纵向布局，而不是改为上下排列后自动改为横向布局呢？

**Comment by KochiyaOcean** [comment]
说实话需求太罕见而且要做成功能很麻烦……
我建议使用自定义 css 解决
设置维持横向布局
```css
kan-game {
    display: block !important;
}
poi-info {
    position: fixed;
    bottom: 0;
    left: 0;
    width: 100%;
    z-index: 100;
}
```
