### ISSUE TITLE
希望界面的布局可以更灵活一点

### ISSUE THREAD

**Issue by deepsea666** [poooi/poi#1692]
**poi 版本 / poi version:8.1.0
**操作系统 / OS:win7 32位
**你遇到了什么样的问题 / The problem you've met:**
希望界面的布局可以更灵活一点
在1440*900的分辨率下poi的布局变的十分别扭，内容都超出显示器范围了
显示设置时切分组件与插件，游戏窗口和面板区域都是100%，缩小后字体会小到看不清
竖版和横版都无法显示全部内容
![22](https://user-images.githubusercontent.com/21211204/35180069-809a859a-fde2-11e7-8336-05d531a1d255.jpg)
![33](https://user-images.githubusercontent.com/21211204/35180070-8a0ef980-fde2-11e7-859a-fef0b0a0674c.jpg)

能否有一个设置模式可以让横版布局时，插件与组件切分时上下排列而不是左右排列，我用PS了一下，希望可以达到如下效果
![11](https://user-images.githubusercontent.com/21211204/35180017-548ae05e-fde1-11e7-9c93-1c1bc2c6a401.jpg)

**Comment by KochiyaOcean** [comment]
自定义 css
```css
.poi-tabs-container {
    flex-direction: column;
    height: calc(100vh - 29px);
}
```
这种布局对窗口高度的需求很高，一般情况下效果不好，所以没有写入本体的打算
