### ISSUE TITLE
关于自定义CSS的问题

### ISSUE THREAD

**Issue by deepsea666** [poooi/poi#1776]
![qq 20180305191758](https://user-images.githubusercontent.com/21211204/36972421-f29e2d1a-20a9-11e8-86c3-7e1ac1e68e31.png)
这个部分的空隙要如何缩小

**Comment by deepsea666** [comment]
用了之后没有变化

**Comment by KochiyaOcean** [comment]
```css
.material-container {
  padding-left: 0!important;
}
```

**Comment by Javran** [comment]
不想用important的话,我用的是这个:

```css
.MainView .resource-panel .material-container {
    padding-left: 0;
}
```
