### ISSUE TITLE
能否给单独弹出的插件窗口也增加这个功能

### ISSUE THREAD

**Issue by deepsea666** [poooi/poi#2124]
**poi 版本 / poi version:**10.2.4

**操作系统 / OS:**win7 64位

poi主体窗口有置顶功能，能否给单独弹出的插件窗口也增加这个功能

此外还有一个问题，我下面截图红框框起来的部分能否通过自定义CSS往上移动到紧贴标题栏
还是9.几的旧版本的时候好像是可以实现的，现在在开发者工具里找不到了
![1001100101](https://user-images.githubusercontent.com/21211204/54969636-e883b300-4fb9-11e9-9c0f-7d0431c32c60.jpg)

**Comment by KagamiChan** [comment]
插件窗口置顶目前没有什么好的方法

可以试一下
```css
kan-game {
  position: absolute !important;
  top: 0 !important;
}
```
